[default.extend-identifiers]
# PCI BARs
BARs = "BARs"

[default.extend-words]
# Package Name, Port Number, etc.
PN = "PN"
pn = "pn"

[type.bitbake.extend-identifiers]
# Package Version
PV = "PV"

[type.c.extend-words]
# Words, often used in Linux kernel
PARM = "PARM"
parms = "parms"
filp = "filp"
dout = "dout"
